fail_fast: true
files: ^src

repos:
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        args: ["--line-length=120"]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ["--max-line-length=120", "--extend-ignore=E203,E402"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
